<?php

declare(strict_types=1);

namespace Paddle\SDK\Tests\DataProvider;

use Paddle\SDK\Notifications\Entities\DeletedPaymentMethod;
use Paddle\SDK\Notifications\Entities\PaymentMethod;
use Paddle\SDK\Notifications\Events\PaymentMethodDeleted;
use Paddle\SDK\Notifications\Events\PaymentMethodSaved;
use Paddle\SDK\Notifications\Events\SubscriptionActivated;
use Paddle\SDK\Notifications\Events\SubscriptionCanceled;
use PHPUnit\Framework\TestCase;

class EventDataProvider extends TestCase
{
    public static function events(): iterable
    {
        $eventTypeData = [
            [
                'address.created',
                'address',
                \Paddle\SDK\Notifications\Events\AddressCreated::class,
                \Paddle\SDK\Notifications\Entities\Address::class,
            ],
            [
                'address.imported',
                'address',
                \Paddle\SDK\Notifications\Events\AddressImported::class,
                \Paddle\SDK\Notifications\Entities\Address::class,
            ],
            [
                'address.updated',
                'address',
                \Paddle\SDK\Notifications\Events\AddressUpdated::class,
                \Paddle\SDK\Notifications\Entities\Address::class,
            ],
            [
                'adjustment.created',
                'adjustment',
                \Paddle\SDK\Notifications\Events\AdjustmentCreated::class,
                \Paddle\SDK\Notifications\Entities\Adjustment::class,
            ],
            [
                'adjustment.updated',
                'adjustment',
                \Paddle\SDK\Notifications\Events\AdjustmentUpdated::class,
                \Paddle\SDK\Notifications\Entities\Adjustment::class,
            ],
            [
                'business.created',
                'business',
                \Paddle\SDK\Notifications\Events\BusinessCreated::class,
                \Paddle\SDK\Notifications\Entities\Business::class,
            ],
            [
                'business.imported',
                'business',
                \Paddle\SDK\Notifications\Events\BusinessImported::class,
                \Paddle\SDK\Notifications\Entities\Business::class,
            ],
            [
                'business.updated',
                'business',
                \Paddle\SDK\Notifications\Events\BusinessUpdated::class,
                \Paddle\SDK\Notifications\Entities\Business::class,
            ],
            [
                'customer.created',
                'customer',
                \Paddle\SDK\Notifications\Events\CustomerCreated::class,
                \Paddle\SDK\Notifications\Entities\Customer::class,
            ],
            [
                'customer.imported',
                'customer',
                \Paddle\SDK\Notifications\Events\CustomerImported::class,
                \Paddle\SDK\Notifications\Entities\Customer::class,
            ],
            [
                'customer.updated',
                'customer',
                \Paddle\SDK\Notifications\Events\CustomerUpdated::class,
                \Paddle\SDK\Notifications\Entities\Customer::class,
            ],
            [
                'discount.created',
                'discount',
                \Paddle\SDK\Notifications\Events\DiscountCreated::class,
                \Paddle\SDK\Notifications\Entities\Discount::class,
            ],
            [
                'discount.imported',
                'discount',
                \Paddle\SDK\Notifications\Events\DiscountImported::class,
                \Paddle\SDK\Notifications\Entities\Discount::class,
            ],
            [
                'discount.updated',
                'discount',
                \Paddle\SDK\Notifications\Events\DiscountUpdated::class,
                \Paddle\SDK\Notifications\Entities\Discount::class,
            ],
            [
                'payment_method.saved',
                'paymentMethod',
                PaymentMethodSaved::class,
                PaymentMethod::class,
            ],
            [
                'payment_method.deleted',
                'paymentMethod',
                PaymentMethodDeleted::class,
                DeletedPaymentMethod::class,
            ],
            [
                'payout.created',
                'payout',
                \Paddle\SDK\Notifications\Events\PayoutCreated::class,
                \Paddle\SDK\Notifications\Entities\Payout::class,
            ],
            [
                'payout.paid',
                'payout',
                \Paddle\SDK\Notifications\Events\PayoutPaid::class,
                \Paddle\SDK\Notifications\Entities\Payout::class,
            ],
            [
                'price.created',
                'price',
                \Paddle\SDK\Notifications\Events\PriceCreated::class,
                \Paddle\SDK\Notifications\Entities\Price::class,
            ],
            [
                'price.updated',
                'price',
                \Paddle\SDK\Notifications\Events\PriceUpdated::class,
                \Paddle\SDK\Notifications\Entities\Price::class,
            ],
            [
                'price.imported',
                'price',
                \Paddle\SDK\Notifications\Events\PriceImported::class,
                \Paddle\SDK\Notifications\Entities\Price::class,
            ],
            [
                'product.created',
                'product',
                \Paddle\SDK\Notifications\Events\ProductCreated::class,
                \Paddle\SDK\Notifications\Entities\Product::class,
            ],
            [
                'product.updated',
                'product',
                \Paddle\SDK\Notifications\Events\ProductUpdated::class,
                \Paddle\SDK\Notifications\Entities\Product::class,
            ],
            [
                'product.imported',
                'product',
                \Paddle\SDK\Notifications\Events\ProductImported::class,
                \Paddle\SDK\Notifications\Entities\Product::class,
            ],
            [
                'subscription.activated',
                'subscription',
                SubscriptionActivated::class,
                \Paddle\SDK\Notifications\Entities\Subscription::class,
            ],
            [
                'subscription.canceled',
                'subscription',
                SubscriptionCanceled::class,
                \Paddle\SDK\Notifications\Entities\Subscription::class,
            ],
            [
                'subscription.created',
                'subscription',
                \Paddle\SDK\Notifications\Events\SubscriptionCreated::class,
                \Paddle\SDK\Notifications\Entities\Subscription::class,
            ],
            [
                'subscription.imported',
                'subscription',
                \Paddle\SDK\Notifications\Events\SubscriptionImported::class,
                \Paddle\SDK\Notifications\Entities\Subscription::class,
            ],
            [
                'subscription.past_due',
                'subscription',
                \Paddle\SDK\Notifications\Events\SubscriptionPastDue::class,
                \Paddle\SDK\Notifications\Entities\Subscription::class,
            ],
            [
                'subscription.paused',
                'subscription',
                \Paddle\SDK\Notifications\Events\SubscriptionPaused::class,
                \Paddle\SDK\Notifications\Entities\Subscription::class,
            ],
            [
                'subscription.resumed',
                'subscription',
                \Paddle\SDK\Notifications\Events\SubscriptionResumed::class,
                \Paddle\SDK\Notifications\Entities\Subscription::class,
            ],
            [
                'subscription.trialing',
                'subscription',
                \Paddle\SDK\Notifications\Events\SubscriptionTrialing::class,
                \Paddle\SDK\Notifications\Entities\Subscription::class,
            ],
            [
                'subscription.updated',
                'subscription',
                \Paddle\SDK\Notifications\Events\SubscriptionUpdated::class,
                \Paddle\SDK\Notifications\Entities\Subscription::class,
            ],
            [
                'transaction.billed',
                'transaction',
                \Paddle\SDK\Notifications\Events\TransactionBilled::class,
                \Paddle\SDK\Notifications\Entities\Transaction::class,
            ],
            [
                'transaction.canceled',
                'transaction',
                \Paddle\SDK\Notifications\Events\TransactionCanceled::class,
                \Paddle\SDK\Notifications\Entities\Transaction::class,
            ],
            [
                'transaction.completed',
                'transaction',
                \Paddle\SDK\Notifications\Events\TransactionCompleted::class,
                \Paddle\SDK\Notifications\Entities\Transaction::class,
            ],
            [
                'transaction.created',
                'transaction',
                \Paddle\SDK\Notifications\Events\TransactionCreated::class,
                \Paddle\SDK\Notifications\Entities\Transaction::class,
            ],
            [
                'transaction.paid',
                'transaction',
                \Paddle\SDK\Notifications\Events\TransactionPaid::class,
                \Paddle\SDK\Notifications\Entities\Transaction::class,
            ],
            [
                'transaction.past_due',
                'transaction',
                \Paddle\SDK\Notifications\Events\TransactionPastDue::class,
                \Paddle\SDK\Notifications\Entities\Transaction::class,
            ],
            [
                'transaction.payment_failed',
                'transaction',
                \Paddle\SDK\Notifications\Events\TransactionPaymentFailed::class,
                \Paddle\SDK\Notifications\Entities\Transaction::class,
            ],
            [
                'transaction.ready',
                'transaction',
                \Paddle\SDK\Notifications\Events\TransactionReady::class,
                \Paddle\SDK\Notifications\Entities\Transaction::class,
            ],
            [
                'transaction.revised',
                'transaction',
                \Paddle\SDK\Notifications\Events\TransactionRevised::class,
                \Paddle\SDK\Notifications\Entities\Transaction::class,
            ],
            [
                'transaction.updated',
                'transaction',
                \Paddle\SDK\Notifications\Events\TransactionUpdated::class,
                \Paddle\SDK\Notifications\Entities\Transaction::class,
            ],
            [
                'report.created',
                'report',
                \Paddle\SDK\Notifications\Events\ReportCreated::class,
                \Paddle\SDK\Notifications\Entities\Report::class,
            ],
            [
                'report.updated',
                'report',
                \Paddle\SDK\Notifications\Events\ReportUpdated::class,
                \Paddle\SDK\Notifications\Entities\Report::class,
            ],
        ];

        foreach ($eventTypeData as [$eventType, $entityProperty, $eventClass, $entityClass]) {
            yield $eventType => [
                $eventType,
                $entityProperty,
                $eventClass,
                $entityClass,
            ];
        }
    }
}
