<?php

declare(strict_types=1);

/**
 * |------
 * | ! Generated code !
 * | Altering this code will result in changes being overwritten |
 * |-------------------------------------------------------------|.
 */

namespace Paddle\SDK\Notifications\Entities\Shared;

use Paddle\SDK\PaddleEnum;

/**
 * @method static CountryCode AD()
 * @method static CountryCode AE()
 * @method static CountryCode AG()
 * @method static CountryCode AI()
 * @method static CountryCode AL()
 * @method static CountryCode AM()
 * @method static CountryCode AO()
 * @method static CountryCode AR()
 * @method static CountryCode AS()
 * @method static CountryCode AT()
 * @method static CountryCode AU()
 * @method static CountryCode AW()
 * @method static CountryCode AX()
 * @method static CountryCode AZ()
 * @method static CountryCode BA()
 * @method static CountryCode BB()
 * @method static CountryCode BD()
 * @method static CountryCode BE()
 * @method static CountryCode BF()
 * @method static CountryCode BG()
 * @method static CountryCode BH()
 * @method static CountryCode BI()
 * @method static CountryCode BJ()
 * @method static CountryCode BL()
 * @method static CountryCode BM()
 * @method static CountryCode BN()
 * @method static CountryCode BO()
 * @method static CountryCode BQ()
 * @method static CountryCode BR()
 * @method static CountryCode BS()
 * @method static CountryCode BT()
 * @method static CountryCode BV()
 * @method static CountryCode BW()
 * @method static CountryCode BZ()
 * @method static CountryCode CA()
 * @method static CountryCode CC()
 * @method static CountryCode CG()
 * @method static CountryCode CH()
 * @method static CountryCode CI()
 * @method static CountryCode CK()
 * @method static CountryCode CL()
 * @method static CountryCode CM()
 * @method static CountryCode CN()
 * @method static CountryCode CO()
 * @method static CountryCode CR()
 * @method static CountryCode CV()
 * @method static CountryCode CW()
 * @method static CountryCode CX()
 * @method static CountryCode CY()
 * @method static CountryCode CZ()
 * @method static CountryCode DE()
 * @method static CountryCode DJ()
 * @method static CountryCode DK()
 * @method static CountryCode DM()
 * @method static CountryCode DO()
 * @method static CountryCode DZ()
 * @method static CountryCode EC()
 * @method static CountryCode EE()
 * @method static CountryCode EG()
 * @method static CountryCode EH()
 * @method static CountryCode ER()
 * @method static CountryCode ES()
 * @method static CountryCode ET()
 * @method static CountryCode FI()
 * @method static CountryCode FJ()
 * @method static CountryCode FK()
 * @method static CountryCode FM()
 * @method static CountryCode FO()
 * @method static CountryCode FR()
 * @method static CountryCode GA()
 * @method static CountryCode GB()
 * @method static CountryCode GD()
 * @method static CountryCode GE()
 * @method static CountryCode GF()
 * @method static CountryCode GG()
 * @method static CountryCode GH()
 * @method static CountryCode GI()
 * @method static CountryCode GL()
 * @method static CountryCode GM()
 * @method static CountryCode GN()
 * @method static CountryCode GP()
 * @method static CountryCode GQ()
 * @method static CountryCode GR()
 * @method static CountryCode GS()
 * @method static CountryCode GT()
 * @method static CountryCode GU()
 * @method static CountryCode GW()
 * @method static CountryCode GY()
 * @method static CountryCode HK()
 * @method static CountryCode HM()
 * @method static CountryCode HN()
 * @method static CountryCode HR()
 * @method static CountryCode HU()
 * @method static CountryCode ID()
 * @method static CountryCode IE()
 * @method static CountryCode IL()
 * @method static CountryCode IM()
 * @method static CountryCode IN()
 * @method static CountryCode IO()
 * @method static CountryCode IQ()
 * @method static CountryCode IS()
 * @method static CountryCode IT()
 * @method static CountryCode JE()
 * @method static CountryCode JM()
 * @method static CountryCode JO()
 * @method static CountryCode JP()
 * @method static CountryCode KE()
 * @method static CountryCode KG()
 * @method static CountryCode KH()
 * @method static CountryCode KI()
 * @method static CountryCode KM()
 * @method static CountryCode KN()
 * @method static CountryCode KR()
 * @method static CountryCode KW()
 * @method static CountryCode KY()
 * @method static CountryCode KZ()
 * @method static CountryCode LA()
 * @method static CountryCode LB()
 * @method static CountryCode LC()
 * @method static CountryCode LI()
 * @method static CountryCode LK()
 * @method static CountryCode LR()
 * @method static CountryCode LS()
 * @method static CountryCode LT()
 * @method static CountryCode LU()
 * @method static CountryCode LV()
 * @method static CountryCode MA()
 * @method static CountryCode MC()
 * @method static CountryCode MD()
 * @method static CountryCode ME()
 * @method static CountryCode MF()
 * @method static CountryCode MG()
 * @method static CountryCode MH()
 * @method static CountryCode MK()
 * @method static CountryCode MN()
 * @method static CountryCode MO()
 * @method static CountryCode MP()
 * @method static CountryCode MQ()
 * @method static CountryCode MR()
 * @method static CountryCode MS()
 * @method static CountryCode MT()
 * @method static CountryCode MU()
 * @method static CountryCode MV()
 * @method static CountryCode MW()
 * @method static CountryCode MX()
 * @method static CountryCode MY()
 * @method static CountryCode MZ()
 * @method static CountryCode NA()
 * @method static CountryCode NC()
 * @method static CountryCode NE()
 * @method static CountryCode NF()
 * @method static CountryCode NG()
 * @method static CountryCode NL()
 * @method static CountryCode NO()
 * @method static CountryCode NP()
 * @method static CountryCode NR()
 * @method static CountryCode NU()
 * @method static CountryCode NZ()
 * @method static CountryCode OM()
 * @method static CountryCode PA()
 * @method static CountryCode PE()
 * @method static CountryCode PF()
 * @method static CountryCode PG()
 * @method static CountryCode PH()
 * @method static CountryCode PK()
 * @method static CountryCode PL()
 * @method static CountryCode PM()
 * @method static CountryCode PN()
 * @method static CountryCode PR()
 * @method static CountryCode PS()
 * @method static CountryCode PT()
 * @method static CountryCode PW()
 * @method static CountryCode PY()
 * @method static CountryCode QA()
 * @method static CountryCode RE()
 * @method static CountryCode RO()
 * @method static CountryCode RS()
 * @method static CountryCode RW()
 * @method static CountryCode SA()
 * @method static CountryCode SB()
 * @method static CountryCode SC()
 * @method static CountryCode SE()
 * @method static CountryCode SG()
 * @method static CountryCode SH()
 * @method static CountryCode SI()
 * @method static CountryCode SJ()
 * @method static CountryCode SK()
 * @method static CountryCode SL()
 * @method static CountryCode SM()
 * @method static CountryCode SN()
 * @method static CountryCode SR()
 * @method static CountryCode ST()
 * @method static CountryCode SV()
 * @method static CountryCode SX()
 * @method static CountryCode SZ()
 * @method static CountryCode TC()
 * @method static CountryCode TD()
 * @method static CountryCode TF()
 * @method static CountryCode TG()
 * @method static CountryCode TH()
 * @method static CountryCode TJ()
 * @method static CountryCode TK()
 * @method static CountryCode TL()
 * @method static CountryCode TM()
 * @method static CountryCode TN()
 * @method static CountryCode TO()
 * @method static CountryCode TR()
 * @method static CountryCode TT()
 * @method static CountryCode TV()
 * @method static CountryCode TW()
 * @method static CountryCode TZ()
 * @method static CountryCode UA()
 * @method static CountryCode UG()
 * @method static CountryCode UM()
 * @method static CountryCode US()
 * @method static CountryCode UY()
 * @method static CountryCode UZ()
 * @method static CountryCode VA()
 * @method static CountryCode VC()
 * @method static CountryCode VG()
 * @method static CountryCode VI()
 * @method static CountryCode VN()
 * @method static CountryCode VU()
 * @method static CountryCode WF()
 * @method static CountryCode WS()
 * @method static CountryCode XK()
 * @method static CountryCode YT()
 * @method static CountryCode ZA()
 * @method static CountryCode ZM()
 */
final class CountryCode extends PaddleEnum
{
    private const AD = 'AD';
    private const AE = 'AE';
    private const AG = 'AG';
    private const AI = 'AI';
    private const AL = 'AL';
    private const AM = 'AM';
    private const AO = 'AO';
    private const AR = 'AR';
    private const AS = 'AS';
    private const AT = 'AT';
    private const AU = 'AU';
    private const AW = 'AW';
    private const AX = 'AX';
    private const AZ = 'AZ';
    private const BA = 'BA';
    private const BB = 'BB';
    private const BD = 'BD';
    private const BE = 'BE';
    private const BF = 'BF';
    private const BG = 'BG';
    private const BH = 'BH';
    private const BI = 'BI';
    private const BJ = 'BJ';
    private const BL = 'BL';
    private const BM = 'BM';
    private const BN = 'BN';
    private const BO = 'BO';
    private const BQ = 'BQ';
    private const BR = 'BR';
    private const BS = 'BS';
    private const BT = 'BT';
    private const BV = 'BV';
    private const BW = 'BW';
    private const BZ = 'BZ';
    private const CA = 'CA';
    private const CC = 'CC';
    private const CG = 'CG';
    private const CH = 'CH';
    private const CI = 'CI';
    private const CK = 'CK';
    private const CL = 'CL';
    private const CM = 'CM';
    private const CN = 'CN';
    private const CO = 'CO';
    private const CR = 'CR';
    private const CV = 'CV';
    private const CW = 'CW';
    private const CX = 'CX';
    private const CY = 'CY';
    private const CZ = 'CZ';
    private const DE = 'DE';
    private const DJ = 'DJ';
    private const DK = 'DK';
    private const DM = 'DM';
    private const DO = 'DO';
    private const DZ = 'DZ';
    private const EC = 'EC';
    private const EE = 'EE';
    private const EG = 'EG';
    private const EH = 'EH';
    private const ER = 'ER';
    private const ES = 'ES';
    private const ET = 'ET';
    private const FI = 'FI';
    private const FJ = 'FJ';
    private const FK = 'FK';
    private const FM = 'FM';
    private const FO = 'FO';
    private const FR = 'FR';
    private const GA = 'GA';
    private const GB = 'GB';
    private const GD = 'GD';
    private const GE = 'GE';
    private const GF = 'GF';
    private const GG = 'GG';
    private const GH = 'GH';
    private const GI = 'GI';
    private const GL = 'GL';
    private const GM = 'GM';
    private const GN = 'GN';
    private const GP = 'GP';
    private const GQ = 'GQ';
    private const GR = 'GR';
    private const GS = 'GS';
    private const GT = 'GT';
    private const GU = 'GU';
    private const GW = 'GW';
    private const GY = 'GY';
    private const HK = 'HK';
    private const HM = 'HM';
    private const HN = 'HN';
    private const HR = 'HR';
    private const HU = 'HU';
    private const ID = 'ID';
    private const IE = 'IE';
    private const IL = 'IL';
    private const IM = 'IM';
    private const IN = 'IN';
    private const IO = 'IO';
    private const IQ = 'IQ';
    private const IS = 'IS';
    private const IT = 'IT';
    private const JE = 'JE';
    private const JM = 'JM';
    private const JO = 'JO';
    private const JP = 'JP';
    private const KE = 'KE';
    private const KG = 'KG';
    private const KH = 'KH';
    private const KI = 'KI';
    private const KM = 'KM';
    private const KN = 'KN';
    private const KR = 'KR';
    private const KW = 'KW';
    private const KY = 'KY';
    private const KZ = 'KZ';
    private const LA = 'LA';
    private const LB = 'LB';
    private const LC = 'LC';
    private const LI = 'LI';
    private const LK = 'LK';
    private const LR = 'LR';
    private const LS = 'LS';
    private const LT = 'LT';
    private const LU = 'LU';
    private const LV = 'LV';
    private const MA = 'MA';
    private const MC = 'MC';
    private const MD = 'MD';
    private const ME = 'ME';
    private const MF = 'MF';
    private const MG = 'MG';
    private const MH = 'MH';
    private const MK = 'MK';
    private const MN = 'MN';
    private const MO = 'MO';
    private const MP = 'MP';
    private const MQ = 'MQ';
    private const MR = 'MR';
    private const MS = 'MS';
    private const MT = 'MT';
    private const MU = 'MU';
    private const MV = 'MV';
    private const MW = 'MW';
    private const MX = 'MX';
    private const MY = 'MY';
    private const MZ = 'MZ';
    private const NA = 'NA';
    private const NC = 'NC';
    private const NE = 'NE';
    private const NF = 'NF';
    private const NG = 'NG';
    private const NL = 'NL';
    private const NO = 'NO';
    private const NP = 'NP';
    private const NR = 'NR';
    private const NU = 'NU';
    private const NZ = 'NZ';
    private const OM = 'OM';
    private const PA = 'PA';
    private const PE = 'PE';
    private const PF = 'PF';
    private const PG = 'PG';
    private const PH = 'PH';
    private const PK = 'PK';
    private const PL = 'PL';
    private const PM = 'PM';
    private const PN = 'PN';
    private const PR = 'PR';
    private const PS = 'PS';
    private const PT = 'PT';
    private const PW = 'PW';
    private const PY = 'PY';
    private const QA = 'QA';
    private const RE = 'RE';
    private const RO = 'RO';
    private const RS = 'RS';
    private const RW = 'RW';
    private const SA = 'SA';
    private const SB = 'SB';
    private const SC = 'SC';
    private const SE = 'SE';
    private const SG = 'SG';
    private const SH = 'SH';
    private const SI = 'SI';
    private const SJ = 'SJ';
    private const SK = 'SK';
    private const SL = 'SL';
    private const SM = 'SM';
    private const SN = 'SN';
    private const SR = 'SR';
    private const ST = 'ST';
    private const SV = 'SV';
    private const SX = 'SX';
    private const SZ = 'SZ';
    private const TC = 'TC';
    private const TD = 'TD';
    private const TF = 'TF';
    private const TG = 'TG';
    private const TH = 'TH';
    private const TJ = 'TJ';
    private const TK = 'TK';
    private const TL = 'TL';
    private const TM = 'TM';
    private const TN = 'TN';
    private const TO = 'TO';
    private const TR = 'TR';
    private const TT = 'TT';
    private const TV = 'TV';
    private const TW = 'TW';
    private const TZ = 'TZ';
    private const UA = 'UA';
    private const UG = 'UG';
    private const UM = 'UM';
    private const US = 'US';
    private const UY = 'UY';
    private const UZ = 'UZ';
    private const VA = 'VA';
    private const VC = 'VC';
    private const VG = 'VG';
    private const VI = 'VI';
    private const VN = 'VN';
    private const VU = 'VU';
    private const WF = 'WF';
    private const WS = 'WS';
    private const XK = 'XK';
    private const YT = 'YT';
    private const ZA = 'ZA';
    private const ZM = 'ZM';
}
