name: Label Checker

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

env:
  VALID_SEMVER_LABELS: norelease,release:major,release:minor,release:patch

permissions:
  contents: read
  issues: read
  pull-requests: read

jobs:
  check_labels:
    name: Check labels
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7
        with:
          script: |
            const validLabels = process.env.VALID_SEMVER_LABELS.split(",");
            const { data: labelResultList } = await github.rest.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });

            const prLabels = labelResultList.map(label => label.name);
            const semverLabels = prLabels.filter(value => validLabels.includes(value));

            core.info(`Valid labels: ${validLabels.join(" | ")}`);
            core.info(`PR labels: ${prLabels.join(" | ")}`);
            core.info(`Semver Labels: ${semverLabels.join(" | ")}`);

            if (semverLabels.length == 0) {
              core.setFailed(`SemVer label missing: You must add one of ${validLabels.join(" | ")} as a label to this PR`);
            }

            if (semverLabels.length > 1) {
              core.setFailed("SemVer label duplicated: You must only add one SemVer label to this PR");
            }
